### PR TITLE
fix: deprecation warnings & GHA python version bump

### PR DESCRIPTION
**Pull request by fherreazcue**
Replaced deprecated set-output and bumped python version in GHA environment variables to 3.11.

### CODE REVIEW

**Review by cjfullerton — APPROVED** [review]
Looks good to me.

Can you update templates in https://github.com/hpcflow/python-release-workflow to reflect these changes?

That way we can update the workflows in hpcflow-new and matflow-new from the same source.

**Comment by cjfullerton** [comment]
Also: it's a good idea to run the build-exes workflow on these branch as an additional test.

**Review by aplowman — APPROVED** [review]
Looks good!

**Comment by fherreazcue** [comment]
Ah yes, I completely forgot about the python-release-workflow... I've created a pull request ([#38](https://github.com/hpcflow/python-release-workflow/pull/38) ) there too now.

**Pull request merged**
