### PR TITLE
Sync with shared docs

### PR DESCRIPTION
**Pull request by fherreazcue**
Updates `docs/source/conf.py` and uses the shared docs remotes (through `.github/remotes.py`) for the first time.

### CODE REVIEW

**Comment by aplowman** [comment]
I think you just need to merge from develop to fix these issues.

**Comment by aplowman** [comment]
Actually the changes to the workflow templates in `.github/workflows/test_direct_sub_python_script.py` and `.github/workflows/test_direct_sub_jupyter_notebook.py` should be discarded; I must have forgotten to sync with `python-release-workflow`. Could you please copy those files from this repo to `python-release-workflow`; and also sync them in matflow (I guess using your new script)? Thanks!

**Comment by fherreazcue** [comment]
Should be done in both repos.

**Review by aplowman — CHANGES_REQUESTED** [review]
For the docs, we can only use Jinja variables (e.g. `{{ app_module }}`) within a jinja context. See `installation.rst` for an example.

**Review by aplowman — APPROVED** [review]

**Pull request merged**
